### ISSUE TITLE
Cannot resolve method 'displayPreview(android.graphics.SurfaceTexture)' in ConversationHelper.Java

### ISSUE THREAD

**Issue by bharatdodeja** [OfficeDev/skype-android-app-sdk-samples#10]
I have followed steps given in read me, but still getting one error in file ConversationHelper.java at line number 353. Screenshot attached for the reference.

<img width="1008" alt="screen shot 2016-07-25 at 2 19 27 pm" src="https://cloud.githubusercontent.com/assets/1468510/17095593/f09017ce-5272-11e6-84ac-5718761973ba.png">

**Comment by bharatdodeja** [comment]
It seems the method has been renamed to showPreview() but not changed in ConversationHelper class.

**Comment by rahulyaa** [comment]
Thanks for reporting this.
Yes this is renamed to showPreview. We will fix this.
