### ISSUE TITLE
Response 500, when trying to join meeting on the guest sample app.

### ISSUE THREAD

**Issue by bhargavms** [OfficeDev/skype-android-app-sdk-samples#14]
08-28 18:40:20.385 17298-17517/com.microsoft.office.sfb.sfbdemo I/[Http] HttpConnection: Got Response: 500 for: Post https://xxx.infra.lync.com/WebTicket/WebTicketService.svc/mex

**Comment by rahulyaa** [comment]
We have a new version of the SDK. Please download and retry. 
Please let me know if this works
