### ISSUE TITLE
Exclude okhttp3 from platform.aar

### ISSUE THREAD

**Issue by dskoneczny** [OfficeDev/skype-android-app-sdk-samples#17]
Hello,
It's possible to exclude okhttp3 from platform.aar file?
I'm using skype with react-native and I have this error message:
`Error:Execution failed for task ':app:transformClassesWithJarMergingForArmDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/Address.class`

**Comment by rahulyaa** [comment]
Thanks for the feedback. I will look into this.
In the meanwhile can you use compile (..) { exclude .. } to unblock yourself?
