### ISSUE TITLE
P2PAnonChat app not working

### ISSUE THREAD

**Issue by vijay559** [OfficeDev/skype-android-app-sdk-samples#23]
ConversationHelper has unresolved symbol errors for the following code. 

     DevicesManager.Endpoint endpoint = DevicesManager.Endpoint.LOUDSPEAKER;
//        switch(this.devicesManager.getActiveEndpoint()) {
//            case LOUDSPEAKER:
//                endpoint = DevicesManager.Endpoint.NONLOUDSPEAKER;
//                break;
//            case NONLOUDSPEAKER:
//                endpoint = DevicesManager.Endpoint.LOUDSPEAKER;
//                break;
//        }
//        this.devicesManager.setActiveEndpoint(endpoint);

Also the Application class has no reference to the methods like joinPeerToPeerAnonymously. 

Was the sample app deprecated and replaced with GuestMeeting sample. ?

**Comment by rahulyaa** [comment]
P2P sample is not the correct sample. It has been removed. We do not support P2P conversations yet
