### ISSUE TITLE
Error code "CALLFAILED".

### ISSUE THREAD

**Issue by ghostring31** [OfficeDev/skype-android-app-sdk-samples#24]
When I tried to connect to audio/video call server returns error code "CALLFAILED" all time in my app and in GuestMeetingJoin sample on Android version 6.0+.
On others versions of Android all working (like 5.0.1, 4.4.4 etc.).

**Comment by rahulyaa** [comment]
@ghostring31 Where do you see the CallFailed error?
Is this an error code returned by some API, or an Alert that you see?

**Comment by ghostring31** [comment]
"CALLFAILED" comes to OnAlertCallback in my anonymousConversation (Coversation class)

**Comment by rahulyaa** [comment]
@ghostring31 Do you see this with the latest version as well? 
We havent heard of this from more users so wondering.

**Comment by ghostring31** [comment]
I'm using last version of SDK -  0.8 Preview

**Comment by rahulyaa** [comment]
Please re-open on if seen on the latest version.
