### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by ghostring31** [OfficeDev/skype-android-app-sdk-samples#25]
Same problem.
https://github.com/OfficeDev/skype-android-app-sdk-samples/issues/12

Using  SDK version 0.7.1 (Preview) (0.7.0.4 on download)

**Comment by rahulyaa** [comment]
@ghostring31 Is this your app?
Few things to confirm:
1. Is your server deployment on-premise?
If Yes to 1, Have you set enablePreviewFeatures(true) in your app?

**Comment by ghostring31** [comment]
No. This problem exists in sample GuestMeetingJoin and in my app.

**Comment by ghostring31** [comment]
Endpoint changes status to LOUDSPEAKER, but microphone not working.

**Comment by ghostring31** [comment]
I solved this problem by:
   -changing build tools version to 2.1.0 ( next steps ~working on newest versions)
   -unmute myself in ParticipantsList in the call
