### ISSUE TITLE
setActiveCamera fails with error since SDK version 0.8

### ISSUE THREAD

**Issue by VincentH-Net** [OfficeDev/skype-android-app-sdk-samples#29]
Camera switching worked in SDK version 0.5 but fails in SDK version 0.8

The video preview starts OK and shows the front camera image.

However, when attempting to switch the camera later with setActiveCamera, that method fails even though canSetActiveCamera returns true. The error in device log says:

IMediaChannel::AttachDevice() failed with error E_MM_NOTSUPPORTED
...
IMediaCallWrapper::setActiveDevice() failed with error E_SetActiveDeviceFailed (E3-7-3)

Is this a defect introduced with the new preview implementation in 0.8?

Full Error Device log:
`12-21 15:05:54.931: I/SFB(16323): INFO MMINTEGRATION CMediaCallWrapper.cpp:1429 (MCWobject:0xc745a120)CMediaCallWrapper::getMediaDirection() returning direction = 3, for mediaType = 6, getNegotiatedConfig = 1.  Result = SUCCESS 0x0
12-21 15:05:54.934: I/SFB(16323): INFO MMINTEGRATION CMediaCallWrapper.cpp:1429 (MCWobject:0xc745a120)CMediaCallWrapper::getMediaDirection() returning direction = 3, for mediaType = 6, getNegotiatedConfig = 1.  Result = SUCCESS 0x0
12-21 15:05:54.934: I/SFB(16323): INFO APPLICATION CUcmpAudioVideoModality.cpp:8796 CUcmpAudioVideoModality::getActiveVideoCaptureDevice() called.
12-21 15:05:54.934: I/SFB(16323): INFO MMINTEGRATION CMediaCallWrapper.cpp:2379 (MCWobject:0xc745a120)CMediaCallWrapper::getActiveAudioDevice() called with MediaType: 6 MediaDirection: 1
12-21 15:05:54.935: I/SFB(16323): INFO APPLICATION CUcmpConversationsManager.cpp:1867 CUcmpConversationsManager::getVideoCaptureDevices() called.
12-21 15:05:54.935: I/SFB(16323): INFO MMINTEGRATION CMediaPlatformWrapper.cpp:525 Number of devices of type (131072), with direction (1) registered with media platform is (2).
12-21 15:05:54.942: I/SFB(16323): INFO MMINTEGRATION CMediaCallWrapper.cpp:1429 (MCWobject:0xc745a120)CMediaCallWrapper::getMediaDirection() returning direction = 3, for mediaType = 6, getNegotiatedConfig = 1.  Result = SUCCESS 0x0
12-21 15:05:54.942: I/SFB(16323): INFO APPLICATION CUcmpAudioVideoModality.cpp:8494 CUcmpAudioVideoModality::setActiveDevice() called.
12-21 15:05:54.943: I/SFB(16323): INFO APPLICATION CUcmpAudioVideoModality.cpp:8566 CUcmpAudioVideoModality::setActiveCaptureDevice() called.
12-21 15:05:54.943: I/SFB(16323): INFO MMINTEGRATION CMediaCallWrapper.cpp:2205 (MCWobject:0xc745a120)CMediaCallWrapper::setAudioDevice() called with MediaDirection 1
12-21 15:05:54.943: E/SFB(16323): ERROR MMINTEGRATION /Volumes/ServerHD2/buildagent/workspace/335323/src/dev/lyncMobile/ucmp/mediamanagerintegration/private/CMediaCallWrapper.cpp:2307 IMediaChannel::AttachDevice() failed with error E_MM_NOTSUPPORTED 0x80070032
12-21 15:05:54.943: E/SFB(16323): ERROR APPLICATION /Volumes/ServerHD2/buildagent/workspace/335323/src/dev/lyncMobile/ucmp/applicationlayer/objectmodel/private/CUcmpAudioVideoModality.cpp:8583 IMediaCallWrapper::setActiveDevice() failed with error E_SetActiveDeviceFailed (E3-7-3)
`

**Comment by rahulyaa** [comment]
@VincentH-Net Thanks for reporting this. This is a known issue that we will address in our next update.

**Comment by rahulyaa** [comment]
@VincentH-Net This is now fixed. Please try it in the latest verison of the AppSDK
