### ISSUE TITLE
W/VideoServiceImpl: canStart. Error code: S_OK

### ISSUE THREAD

**Issue by vipulasri** [OfficeDev/skype-android-app-sdk-samples#3]
I mostly get this error when, Preview Texture View is loaded. Since i am getting this error, i am unable to see the Preview View. 
`
W/VideoServiceImpl: canStart. Error code: S_OK`

**Comment by richardtaylorrt** [comment]
Hi - sorry you're having problems.  Are you running one of the sample apps?  Which one?
Have you followed all the set up instructions in the app's readme file?  If you're still hitting problems, please can you send device logs - and details of the steps to repro - to [Skype Developer Insiders]( Skype developer insiders email box).  Thanks.

**Comment by vipulasri** [comment]
Hello @richardtaylorrt I am using [GuestMeetingJoin](https://github.com/OfficeDev/skype-android-app-sdk-samples/tree/master/GuestMeetingJoin) sample code. I was able to run the code correctly and somehow it was working fine. After 2 subsequent runs/execution of code on device I am facing this error. And Link provided by you in previous comment for Skype Developer Insiders its showing 404 Page not found.

**Comment by richardtaylorrt** [comment]
Hi - apologies, I've now fixed the link above.  Please email skypedevinsiders@microsoft.com with device logs and repro steps for this error.  Thanks.
