### ISSUE TITLE
USB Camera support

### ISSUE THREAD

**Issue by ckoessler** [OfficeDev/skype-android-app-sdk-samples#42]
Hello,
I am trying the run the sample app (HealthCare App) using a Logitech HD Pro Webcam C920 camera plugged on my Android device's USB port. The camera does not load.

I tried calling `videoService.getActiveCamera();` and got the following error:
```
IMediaCallWrapper::getActiveDevice() failed with error E_Unexpected (E0-0-11)
```

My device runs 7.0

**Comment by rahulyaa** [comment]
@ckoessler We do not support external camera. The enum has the "external" property for future expansion. The documentation unfortunately did not mention this is for future releases. 
At this time, there is no timeline set for external camera support.

**Comment by rahulyaa** [comment]
See comment above.
