### ISSUE TITLE
could not load library "libsqlcipher.so"

### ISSUE THREAD

**Issue by techlectdinesh** [OfficeDev/skype-android-app-sdk-samples#44]
com.microsoft.office.sfb.sfbdemo E/dalvikvm: dlopen("/data/app-lib/com.microsoft.office.sfb.sfbdemo-2/libacomo.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1636): could not load library "libsqlcipher.so" needed by "libacomo.so"; caused by load_library(linker.cpp:746): library "libsqlcipher.so" not found

**Comment by techlectdinesh** [comment]
Hello everyone final i have resolve this issue.
 Here is the problem in Application class - 

private static boolean LoadNativeLibrary() {
        try {
            if(!sLibComoIsLoaded.get()) {
                System.loadLibrary("gnustl_shared");
                System.loadLibrary("roottools");
                System.loadLibrary("RtmMediaManagerDyn");
                System.loadLibrary("acomo");
                sLibComoIsLoaded.set(true);
            }
        } catch (UnsatisfiedLinkError var2) {
            String strException = "Failed to load native library";
            throw new RuntimeException(strException);
        }

        return sLibComoIsLoaded.get();
    }

There is missing 

System.loadLibrary("sqlcipher");

please add this line before 

System.loadLibrary("sqlcipher");

            this.application = Application.getInstance(this.getApplication().getApplicationContext());

**Comment by rahulyaa** [comment]
@techlectdinesh I don't think you need to do that. Which version of the sdk are you using?

**Comment by techlectdinesh** [comment]
Hi @rahulyaa 
i am using SkypeForBusinessAppSDKAndroid-1.1.0.0

**Comment by rahulyaa** [comment]
@techlectdinesh Is this resolved? If yes, what was the issue?
