### ISSUE TITLE
participant's displayname is empty 

### ISSUE THREAD

**Issue by guoGavin** [OfficeDev/skype-android-app-sdk-samples#5]
this.participantItemList.addOnListChangedCallback(listChangeListener);

When there is a person entering the meeting room

onItemRangeInserted() will be called.

but，the name of the person who has just joined is empty.

why?

**Comment by rahulyaa** [comment]
Hi Gavin,

Please share the logs.

We have a bug in the SDK currently where the participant name is empty. We are planning to fix it in future releases.

I can confirm if this is the same issue you are seeing.

Thank you.

Get Outlook for Mobile<https://aka.ms/cq8ksb>

From: gavin guo
Sent: Thursday, June 16, 8:18 PM
Subject: [OfficeDev/skype-android-app-sdk-samples] participant's displayname is empty (#5)
To: OfficeDev/skype-android-app-sdk-samples

this.participantItemList.addOnListChangedCallback(listChangeListener);

When there is a person entering the meeting room

onItemRangeInserted() will be called.

but?the name of the person who has just joined is empty.

why?

-

**Comment by guoGavin** [comment]
hi，rahulyaa，

logs?how can I collect them?

There is no mistake.

Just getting the data is empty.

I will try to collect them,however, please give me some advice。

Thanks

**Comment by rahulyaa** [comment]
Sorry, this is an older issue. Please try with the latest version of the SDK and let me know if you still see an empty display name.

**Comment by guoGavin** [comment]
Already in version 0.8 or higher
