### ISSUE TITLE
Video escalation between two ATTENDEES with an Android and an iOS devices not working

### ISSUE THREAD

**Issue by fabiomercorillo** [OfficeDev/skype-android-app-sdk-samples#50]
Hi,
in my use case I make a video escalation between 2 attendees using an Android and an iOS devices. After video service started with success for each participant, 
in which everyone subscribe itself to the video streaming of the other participant, the video preview and the surface connected to the remote participant work fine for few seconds, 
but after rendering some video frames the video service of Android participants change unexpectedly its status to DISCONNECTED, without exceptions. 
Tested on Samsung S6 (Android 6) and iPhone 6S (iOS 10.3.2).

After restart the video, the streaming work fine.

The same scenario between Android SDK (ATTENDEE) and Web SDK (LEADER) work fine without errors.

**Comment by praween05** [comment]
Hello,

I am also facing the same issue. I am not able to see or listen other participant video or audio. It is just appearing as a black player container. I have tried joining the meeting using the iOS device and using an Android device. Android user is not able to see the video of iOS participants.

FYI we both user can chat in the same meeting room

**Comment by rahulyaa** [comment]
@fabiomercorillo @praween05 We have an internal report about this. The culprit right now is the Samsung devices. We need some logs for the issue. Collect logs:

1.       /sdcard/Android/data/[Your App ID]/cache/[Your App ID].blog
There could be multiple .blog files, please grab all of them.

2.       /data/data/[Your App ID]/Tracing/*.log
All .log files at this location.

E.g.
adb shell "run-as com.microsoft.office.sfb.sfbdemo ls /data/data/com.microsoft.office.sfb.sfbdemo/Tracing"

Please share these.  Thanks a lot.

**Comment by paollika** [comment]
Unfortunately this same error goes with another Android devices as weel, like we've tried sony's device with the same black screen error too.

**Comment by jovillas** [comment]
Hi, could you share the logs so we can investigate the issue?

**Comment by paollika** [comment]
Hi,


Please find attached the logs from this problem.


Logs are taken from the

Device: Samsung Galaxy Tab S3 (SM-T825)
Android version: 7.0


Please do note that there are some customer spesific information in these, so do not share or publish them in the gitHub.


Br,


Pasi


________________________________
Lähettäjä: Jorge Villasenor <notifications@github.com>
Lähetetty: 4. elokuuta 2017 2:24
Vastaanottaja: OfficeDev/skype-android-app-sdk-samples
Kopio: Pasi Ollikainen; Comment
Aihe: Re: [OfficeDev/skype-android-app-sdk-samples] Video escalation between two ATTENDEES with an Android and an iOS devices not working (#50)


Hi, could you share the logs so we can investigate the issue?

**Comment by jovillas** [comment]
Hi @paollika I see you responded through email. It seems github doesn't [support](https://github.com/blog/811-reply-to-comments-from-email) emal attachments and it just ignore them.

Could you attach the logs directly on the github webpage? As I see on their [docs](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/), not all file formats are supported but a zip file should be good.

**Comment by jovillas** [comment]
hi @paollika could you send me the logs to my email directly? jovillas@microsoft.com

I haven't been able to find a S6 device to test, I'm testing with a S4 and haven't been able to reproduce it. Can you think on something else, aside of the device version, that can be specific to your environment? And just to confirm, is this happening with the GuestMeetingJoin, the HealthcareApp demo or on a different application?

**Comment by jovillas** [comment]
Hi all, I found a way to reproduce this issue, but I would like to confirm if this is what is happening on your applications.

On the GuessMeetingJoin application, we subscribe only to the Leader participant, you can see it  [here](https://github.com/OfficeDev/skype-android-app-sdk-samples/blob/master/GuestMeetingJoin/sfbdemo/src/main/java/com/microsoft/office/sfb/sfbdemo/VideoFragment.java#L257), if there is no Leader on the meeting, the demo will not subscribe to any participant video, and thus, will just show a black box.

If I change that line to subscribe to the first Attendee, it shows the video from the iOS device, the other participant on the meeting.
`
if (participant.getRole() == Participant.Role.ATTENDEE) {...}
`

Can you confirm your app is subscribing to an active participant?

**Comment by jovillas** [comment]
Talked with @paollika offline and the issue was fixed on their side.
