### ISSUE TITLE
Allow Multiple users for Video

### ISSUE THREAD

**Issue by Amihir1** [OfficeDev/skype-android-app-sdk-samples#51]
Currently in this application only 2 video stream is shown, Is it possible that i can shown all members video who join the meeting? 

If yes ,then can you please share some guidelines or code???

**Comment by rahulyaa** [comment]
Yes you can. Similar to the sample, you can subscribe to each participants video. Take a look at the sfmdemo project, VideoFragment.java, VideoStreamSurfaceCreatedCallback method.

**Comment by Amihir1** [comment]
@rahulyaa  I have created another MMVRSurfaceView , i want to show 4 users video, Is there any thing for 
Participant.Role.LEADER that i need to change.  

If possible can you please share some code. Thanks in advance.

**Comment by Amihir1** [comment]
@rahulyaa  I have make some changes in the method, Please check below code.

public void VideoStreamSurfaceCreatedCallback(MMVRSurfaceView mmvrSurfaceView) {
        this.mmvrSurfaceView = mmvrSurfaceView;
        this.mmvrSurfaceView.setAutoFitMode(MMVRSurfaceView.MMVRAutoFitMode_Crop);
        this.mmvrSurfaceView.requestRender();
        try {
            for (Participant participant : this.remoteParticipants) {
                //if (participant.getRole() == Participant.Role.LEADER) {
                    Person p=participant.getPerson();
                    String nm=p.getDisplayName();
                    if(nm.equalsIgnoreCase("user1")) {
                        this.remoteParticipantLeader = participant;
                        ParticipantVideo participantVideo = this.remoteParticipantLeader.getParticipantVideo();
                        participantVideo.subscribe(this.mmvrSurfaceView);
                    }else if(nm.equalsIgnoreCase("user2")) {
                        this.remoteParticipantLeader2 = participant;
                        ParticipantVideo participantVideo = this.remoteParticipantLeader2.getParticipantVideo();
                        participantVideo.subscribe(this.mmvrSurfaceView2);
                    }
                    else if(nm.equalsIgnoreCase("user3")) {
                        this.remoteParticipantLeader3 = participant;
                        ParticipantVideo participantVideo = this.remoteParticipantLeader3.getParticipantVideo();
                        participantVideo.subscribe(this.mmvrSurfaceView3);
                    }
                    break;
                //}
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
        this.getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
                updateState();
            }
        });

    }

But in video preview it shows only black , nothing else, Let me know what is wrong i am doing???
Please reply asap, I am waiting for the response.

**Comment by rahulyaa** [comment]
@Amihir1 Did you resolve this? All all the participants in the meeting leaders? 
Participant.Role.LEADER
