### ISSUE TITLE
videoService canStart/canStop always returning false since 1.3.0.0

### ISSUE THREAD

**Issue by dcchristopher** [OfficeDev/skype-android-app-sdk-samples#55]
Everything is working fine using the 1.1.0.0 AARs/JARs. Updating to 1.3.0.0 appears to affect the video service and its ability to send video. I never used the built-in conversation helper in Android because I had to make enough modifications / extensions to support our use cases. Nevertheless, my version of the helper worked flawlessly (currently in production) up to the moment I tried to upgrade to 1.3.0.0. The mobile app now receives video but does not appear to transmit it (although the local preview works). My property change callback for the conversation shows that the CAN_START and CAN_STOP properties are flagged repeatedly but canStart() and canStop always return false. That's odd, right? At least ONE of them ought to be true (once the connection is established and things have settled). Logs attached. Thank you in advance. P.S. Identifying information has been intentionally obfuscated.
[app_log.log](https://github.com/OfficeDev/skype-android-app-sdk-samples/files/1338454/app_log.log)

**Comment by dcchristopher** [comment]
So the first time I glanced at the logs I could not really see anything useful. I stepped away and came back and did notice that canStart was throwing error codes. Initially it throws E_BootstrapInProgress which makes sense. Once the conversation data starts to flow though, it continues to throw E_ActionNotAvailable. I don't know if that's equivalent to saying "well, it has already started so it can't start again" but if that were the case, then canStop() would return eventually true. What are the other reasons canStart could throw E_ActionNotAvailable and why would that have changed from 1.1 to 1.3? Just thinking out loud, here.

**Comment by jihadrhamza** [comment]
Any update on this issue?

**Comment by dcchristopher** [comment]
Well, this is not an issue with 1.4.0.0 so ... case closed?

**Comment by dcchristopher** [comment]
Follow-up note ... this "issue" is still present in 1.4.0.0 (I don't know why I got lucky on the first try but it hasn't worked since). The root cause however is that I was expecting a VideoService.CAN_START_PROPERTY_ID => true to trigger the unpausing of the video so that the connection can be considered "established". I have updated the code to also accept a VideoService.CAN_STOP_PROPERTY_ID => true as a trigger. The conclusion is, you may never be notified that the video service "can" be started but it may have already started.
