### ISSUE TITLE
implementing sign in on healthcare app

### ISSUE THREAD

**Issue by asebak** [OfficeDev/skype-android-app-sdk-samples#6]
I noticed that the sign in page doesn't really authenticate.  How would I go about authenticating the skype for business credentials for a user and password?  At the same time how do you get the context of this signed in user such as contact list, their groups, etc?

**Comment by rahulyaa** [comment]
Hi Ahmad,

The SDK does not support authenticated scenarios.

It currently only supports Anonymous Meeting Join.

We plan to add this in future releases, but there is no date for it yet.

Thanks
Rahul

**Comment by asebak** [comment]
ok thanks for the information!
