### ISSUE TITLE
Failed to resolve: :SkypeForBusinessTelemetryService:

### ISSUE THREAD

**Issue by rahulkushwaha482** [OfficeDev/skype-android-app-sdk-samples#64]
I got this error while opening this app in Android Studio First Time. What is the cause and better solution for that? Please resolve my problem. I got these issues:-
Failed to resolve: :SkypeForBusinessTelemetryService:

Failed to resolve: :SkypeForBusiness: |  
-- | --
Failed to resolve: :SkypeForBusinessTelemetryService: |  
Failed to resolve: :SkypeForBusinessNative: |  
Failed to resolve: :SkypeForBusinessPlatform: |  
Failed to resolve: :SkypeForBusinessNativeEnums: |  
Failed to resolve: :SkypeForBusinessTelemetryClient: |  
Failed to resolve: :android-database-sqlcipher: |  
Failed to resolve: :SkypeForBusinessInjector: |

**Comment by EngMohadese** [comment]
@rahulkushwaha482 did you find the answer?

**Comment by rahulkushwaha482** [comment]
@EngMohadese  Yes I resolved this .

**Comment by TheVirtuoso27** [comment]
> @EngMohadese Yes I resolved this .

How :v

**Comment by Yashshree** [comment]
How?? GettingSame Error..
