### ISSUE TITLE
Doctors video is not showing in Health care sample

### ISSUE THREAD

**Issue by dheran** [OfficeDev/skype-android-app-sdk-samples#8]
Hi,

I tried both Lamna health care sample and guest meeting join. and I used skype for business basic client on other end. I created meeting link via skype desktop and configured the link in both apps. 

I noticed, video from mobile phone was shown in Skype desktop client but video from skype desktop client was not showing in the app.

**Comment by rahulyaa** [comment]
In the guest meeting join sample, do you immediately navigate to the video view after the meeting is joined? What happens if you wait a few secs (say 10) and then switch to the video view?
Same on the video view, what happens if you wait a bit?

**Comment by dheran** [comment]
@rahulyaa  I'm getting following error while clicking "VIDEO" button after 1min in guest meeting sample.

> 07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err: com.microsoft.office.sfb.appsdk.SFBException: setPaused Failed.
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at com.microsoft.office.sfb.appsdk.VideoServiceImpl.setPaused(VideoServiceImpl.java:148)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at com.microsoft.office.sfb.sfbdemo.VideoFragment.SurfaceTextureCreatedCallback(VideoFragment.java:234)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at com.microsoft.office.sfb.sfbdemo.VideoFragment$VideoPreviewSurfaceTextureListener.onSurfaceTextureAvailable(VideoFragment.java:113)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:370)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15443)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1049)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16539)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15466)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:15461)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.getDisplayList(View.java:15488)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.View.draw(View.java:16258)
07-04 10:42:34.184 12536-12536/com.microsoft.office.sfb.sfbdemo W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3713)

**Comment by rahulyaa** [comment]
Are you still seeing this issue?

**Comment by dheran** [comment]
@rahulyaa I found if provider got no mic means, this issue is happening. 

And one more thing, Currently video gets stretched to the size of the parent layout (eg surfaceview) and not maintaining the video aspect ratio. How can I fix this?

**Comment by jmsalcido** [comment]
I had this problem with a skype4biz meeting, I created another meeting with Outlook and it worked correctly, but the mic was off.
